In [9]:
import pandas as pd
import datasets

print("pandas:", pd.__version__)
print("datasets:", datasets.__version__)

pandas: 3.0.5
datasets: 5.0.1

In [10]:
from datasets import load_dataset

english_dataset = load_dataset(
    "goosmanlei/amazon_reviews_multi",
    "en"
)

In [11]:
df_en = english_dataset["train"].to_pandas()

df_en.shape

(200000, 8)

In [12]:
df_en.head()

,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,en_0964290,product_en_0740675,reviewer_en_0342986,1,Arrived broken. Manufacturer defect. Two of th...,I'll spend twice the amount of time boxing up ...,en,furniture
1,en_0690095,product_en_0440378,reviewer_en_0133349,1,the cabinet dot were all detached from backing...,Not use able,en,home_improvement
2,en_0311558,product_en_0399702,reviewer_en_0152034,1,I received my first order of this product and ...,The product is junk.,en,home
3,en_0044972,product_en_0444063,reviewer_en_0656967,1,This product is a piece of shit. Do not buy. D...,Fucking waste of money,en,wireless
4,en_0784379,product_en_0139353,reviewer_en_0757638,1,went through 3 in one day doesn't fit correct ...,bubble,en,pc

In [13]:
df_en.columns

Index(['review_id', 'product_id', 'reviewer_id', 'stars', 'review_body',
       'review_title', 'language', 'product_category'],
      dtype='str')

In [14]:
sample_en = (
    df_en
    .groupby("stars", group_keys=False)
    .apply(lambda x: x.sample(n=60, random_state=42))
    .reset_index(drop=True)
)

In [15]:
print(df_en.columns.tolist())

['review_id', 'product_id', 'reviewer_id', 'stars', 'review_body', 'review_title', 'language', 'product_category']

In [16]:
df_en.head()

,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,en_0964290,product_en_0740675,reviewer_en_0342986,1,Arrived broken. Manufacturer defect. Two of th...,I'll spend twice the amount of time boxing up ...,en,furniture
1,en_0690095,product_en_0440378,reviewer_en_0133349,1,the cabinet dot were all detached from backing...,Not use able,en,home_improvement
2,en_0311558,product_en_0399702,reviewer_en_0152034,1,I received my first order of this product and ...,The product is junk.,en,home
3,en_0044972,product_en_0444063,reviewer_en_0656967,1,This product is a piece of shit. Do not buy. D...,Fucking waste of money,en,wireless
4,en_0784379,product_en_0139353,reviewer_en_0757638,1,went through 3 in one day doesn't fit correct ...,bubble,en,pc

In [17]:
sample_en = (
    df_en
    .groupby("stars", group_keys=False)
    .sample(n=60, random_state=42)
    .reset_index(drop=True)
)

In [18]:
sample_en["stars"].value_counts().sort_index()

stars
1    60
2    60
3    60
4    60
5    60
Name: count, dtype: int64

In [19]:
sample_en.shape

(300, 8)

In [20]:
annotation_en = sample_en[
    [
        "review_id",
        "review_title",
        "review_body",
        "language",
        "product_category"
    ]
].copy()

annotation_en["sentiment_label"] = ""
annotation_en["confidence"] = ""
annotation_en["notes"] = ""

annotation_en.head()

,review_id,review_title,review_body,language,product_category,sentiment_label,confidence,notes
0,en_0853851,I don’t recomend,I did receive the item and it says it did arri...,en,other,,,
1,en_0737292,Will block screen if there are screens on the ...,The difficulty I had with using these is that ...,en,luggage,,,
2,en_0574934,"Missing glove, dirty guard, customer service MIA",Did not include the safety glove promised in t...,en,kitchen,,,
3,en_0561880,Received questionable email from Amazon.com pe...,I received an email from Amazon.com stating th...,en,other,,,
4,en_0007287,Floaters,"They float. The bag says they don’t, but they ...",en,lawn_and_garden,,,

In [21]:
print(annotation_en.shape)
print(annotation_en.columns.tolist())

(300, 8)
['review_id', 'review_title', 'review_body', 'language', 'product_category', 'sentiment_label', 'confidence', 'notes']

In [22]:
sample_en.to_csv(
    "../data/raw/amazon_reviews_en_ground_truth_300.csv",
    index=False,
    encoding="utf-8-sig"
)

In [23]:
annotation_en.to_csv(
    "../data/annotation/amazon_reviews_en_annotation_300.csv",
    index=False,
    encoding="utf-8-sig"
)

In [24]:
import os

print(os.path.exists("../data/raw/amazon_reviews_en_ground_truth_300.csv"))
print(os.path.exists("../data/annotation/amazon_reviews_en_annotation_300.csv"))

True
True

In [25]:
annotation_en = (
    annotation_en
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

In [26]:
annotation_en = (
    annotation_en
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

annotation_en.to_csv(
    "../data/annotation/amazon_reviews_en_annotation_300.csv",
    index=False,
    encoding="utf-8-sig"
)

In [27]:
from datasets import load_dataset

chinese_dataset = load_dataset(
    "goosmanlei/amazon_reviews_multi",
    "zh"
)

In [28]:
df_zh = chinese_dataset["train"].to_pandas()

print(df_zh.shape)
print(df_zh.columns.tolist())

df_zh.head()

(200000, 8)
['review_id', 'product_id', 'reviewer_id', 'stars', 'review_body', 'review_title', 'language', 'product_category']

,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,zh_0626061,product_zh_0691762,reviewer_zh_0824776,1,本人账号被盗，资金被江西（杨建）挪用，请亚马逊尽快查实，将本人的200元资金退回。本人已于2...,此书不是本人购买,zh,book
1,zh_0713738,product_zh_0123483,reviewer_zh_0518940,1,这简直就是太差了！出版社怎么就能出版吗？我以为是百度摘录呢！这到底是哪个鱼目混珠的教授啊？！...,简直是废话！,zh,book
2,zh_0621612,product_zh_0670618,reviewer_zh_0040023,1,购买页面显示1～2日发货，付款之后显示半个月后送达，实际收到商品距离下单日期已经一个多月。 ...,最牛逼的预售,zh,home_improvement
3,zh_0757997,product_zh_0379151,reviewer_zh_0794363,1,音箱播放时断断续续的！质量完全不行，第一次在亚马逊买东西，晕！怎么是这样的呀？有客服和我联系吗？,迷你音响,zh,other
4,zh_0086548,product_zh_0280958,reviewer_zh_0726131,1,字太小啦，建议买别的版本，慎买呀，亲们，我后悔买了这个版本！！！,排版太密，不适合菜鸟用，看到眼睛花了！,zh,book

In [29]:
sample_zh = (
    df_zh
    .groupby("stars", group_keys=False)
    .sample(n=60, random_state=42)
    .reset_index(drop=True)
)

In [30]:
sample_zh["stars"].value_counts().sort_index()

stars
1    60
2    60
3    60
4    60
5    60
Name: count, dtype: int64

In [31]:
sample_zh.shape

(300, 8)

In [32]:
annotation_zh = sample_zh[
    [
        "review_id",
        "review_title",
        "review_body",
        "language",
        "product_category"
    ]
].copy()

annotation_zh["sentiment_label"] = ""
annotation_zh["confidence"] = ""
annotation_zh["notes"] = ""

In [33]:
annotation_zh = (
    annotation_zh
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

In [34]:
print(annotation_zh.shape)
print(annotation_zh.columns.tolist())

annotation_zh.head()

(300, 8)
['review_id', 'review_title', 'review_body', 'language', 'product_category', 'sentiment_label', 'confidence', 'notes']

,review_id,review_title,review_body,language,product_category,sentiment_label,confidence,notes
0,zh_0958913,感觉还行,某些细节处有线头，布的材质较软，不是想象中那种较硬的帆布，所以实物没有图片看起来那么板正，另...,zh,shoes,,,
1,zh_0133459,还不错,平时穿运动鞋42的，皮鞋41的，clarks鞋子一直穿8.5，这双选了8.5刚好。不像评论里...,zh,shoes,,,
2,zh_0971712,学mongodb不建议买,书质量很好，但是内容小错不断，有时候容易迷惑，如果是初学者会很费劲,zh,book,,,
3,zh_0135694,好小,没注意量，以为和超市卖的茄汁罐头一样大，结果好小，太迷你了，虽然挂着进口2字，但比超市大分量...,zh,grocery,,,
4,zh_0884672,设计美观、简洁，内容完整无删节,好好的书，送到手时书皮都折了，书角还开裂了！好心疼呜呜呜，只能赶紧用透明胶封一下。除此之外一...,zh,book,,,

In [35]:
sample_zh.to_csv(
    "../data/raw/amazon_reviews_zh_ground_truth_300.csv",
    index=False,
    encoding="utf-8-sig"
)

In [36]:
annotation_zh.to_csv(
    "../data/annotation/amazon_reviews_zh_annotation_300.csv",
    index=False,
    encoding="utf-8-sig"
)

In [37]:
import os

print(os.path.exists("../data/raw/amazon_reviews_zh_ground_truth_300.csv"))
print(os.path.exists("../data/annotation/amazon_reviews_zh_annotation_300.csv"))

True
True

In [38]:
import pandas as pd

df_ko = pd.read_csv(
    "../data/raw/ratings_train.txt",
    sep="\t"
)

print(df_ko.shape)
print(df_ko.columns.tolist())

df_ko.head()

(150000, 3)
['id', 'document', 'label']

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [39]:
df_ko.isnull().sum()

id          0
document    5
label       0
dtype: int64

In [40]:
df_ko = df_ko.dropna(subset=["document"]).copy()

In [41]:
df_ko["label"].value_counts().sort_index()

label
0    75170
1    74825
Name: count, dtype: int64

In [42]:
sample_ko = (
    df_ko
    .groupby("label", group_keys=False)
    .sample(n=150, random_state=42)
    .reset_index(drop=True)
)

In [43]:
sample_ko["label"].value_counts().sort_index()

label
0    150
1    150
Name: count, dtype: int64

In [44]:
sample_ko.shape

(300, 3)

In [45]:
annotation_ko = sample_ko[
    ["id", "document"]
].copy()

annotation_ko = annotation_ko.rename(
    columns={
        "id": "review_id",
        "document": "review_body"
    }
)

annotation_ko["review_title"] = ""
annotation_ko["language"] = "ko"
annotation_ko["product_category"] = "movie"
annotation_ko["sentiment_label"] = ""
annotation_ko["confidence"] = ""
annotation_ko["notes"] = ""

In [46]:
annotation_ko = annotation_ko[
    [
        "review_id",
        "review_title",
        "review_body",
        "language",
        "product_category",
        "sentiment_label",
        "confidence",
        "notes"
    ]
]

In [47]:
annotation_ko = (
    annotation_ko
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

In [48]:
print(annotation_ko.shape)
print(annotation_ko.columns.tolist())

annotation_ko.head()

(300, 8)
['review_id', 'review_title', 'review_body', 'language', 'product_category', 'sentiment_label', 'confidence', 'notes']

,review_id,review_title,review_body,language,product_category,sentiment_label,confidence,notes
0,8363132,,진짜 괜찮은데.. 휴 가슴이 답답해질정도로 많은 생각하게 되네요,ko,movie,,,
1,9473399,,BLACK ... 불가능이란건없네요,ko,movie,,,
2,5030353,,갠적으론 8점정도.. 평점이 넘낮아 10점.,ko,movie,,,
3,315189,,호러다큐멘터리라고 잔뜩기대했지만. 호러가 아니었다;,ko,movie,,,
4,4910465,,원작 만화의 원래 제목이 나오코임. 한국에선 스타트로 출간.,ko,movie,,,

In [49]:
sample_ko.to_csv(
    "../data/raw/nsmc_ko_ground_truth_300.csv",
    index=False,
    encoding="utf-8-sig"
)

In [50]:
annotation_ko.to_csv(
    "../data/annotation/nsmc_ko_annotation_300.csv",
    index=False,
    encoding="utf-8-sig"
)